name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #       checkout
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      #       build project and run all tests & checks
      - name: Maven Verify
        working-directory: server
        run: mvn -B clean verify

##       Upload code coverage report to Codecov
#      - name: Test Coverage
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}