name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: deadline_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Build project and run all tests & checks
      - name: Maven Verify
        working-directory: server
        env:
          DB_URL: jdbc:postgresql://localhost:5432/deadline_db
          DB_USER: postgres
          DB_PASSWORD: 1234
        run: mvn -B clean verify

      ## Upload code coverage report to Codecov (optional)
      # - name: Test Coverage
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: $